export const types = {
    INICIALIZAR_DATA: 'INICIALIZAR_DATA',
    AGREGAR_TITULAR: 'AGREGAR_TITULAR',
    ELIMINAR_TITULAR: 'ELIMINAR_TITULAR',
    AGREGAR_SUPLENTE: 'AGREGAR_SUPLENTE',
    ELIMINAR_SUPLENTE: 'ELIMINAR_SUPLENTE',
    OBTENER_DATOS_GRILLA: 'OBTENER_DATOS_GRILLA',
    FILTRAR_GRILLA: 'FILTRAR_GRILLA',
    PAGINAR: 'PAGINAR',
    INSERTAR_REGISTRO: 'INSERTAR_REGISTRO',
    ACTUALIZAR_REGISTRO: 'ACTUALIZAR_REGISTRO',
    ELIMINAR_REGISTRO: 'ELIMINAR_REGISTRO',
    EDITAR_REGISTRO: 'EDITAR_REGISTRO',
}